# Use Node.js as the base image
FROM node:23-alpine

# Set working directory
WORKDIR /app

# Copy package.json and install dependencies
COPY package*.json ./
RUN npm install

# Copy all other files
ADD . .


# Start the application
CMD ["node", "server.js"]
