version: '3.8'

services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile-front
    ports:
      - "3000:3000"
    depends_on:
      - backend
    networks:
      - app-network
    restart: always

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile-back
    ports:
      - "5000:5000"
    networks:
      - app-network
    restart: always

networks:
  app-network:
    driver: bridge
  
